"""phase 2 booking schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-10 21:06:41.312081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('airbnb', 'vrbo', name='platform'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('guest_first_name', sa.String(length=128), nullable=False),
    sa.Column('guest_last_name', sa.String(length=128), nullable=False),
    sa.Column('guest_phone', sa.String(length=64), nullable=True),
    sa.Column('guest_email', sa.String(length=256), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', name='booking_status'), server_default='active', nullable=False),
    sa.Column('source_email_message_id', sa.String(length=128), nullable=False),
    sa.Column('cancellation_email_message_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancellation_email_message_id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_bookings_platform_external_id'),
    sa.UniqueConstraint('source_email_message_id')
    )
    op.create_index('ix_bookings_check_in_date', 'bookings', ['check_in_date'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_table('booking_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('owner_alert_new_booking', 'docusign_send', 'docusign_void', 'cleaner_sheet_add', 'access_code_create', 'access_code_delete', 'hoa_email', 'owner_alert_missing_phone_7d', 'owner_alert_missing_phone_4d', 'owner_alert_missing_email_7d', 'owner_alert_missing_email_4d', 'owner_alert_docusign_unsigned_7d', 'owner_alert_docusign_unsigned_4d', 'owner_alert_cancellation_hoa', 'owner_alert_cancellation_cleaner', name='task_type'), nullable=False),
    sa.Column('state', sa.Enum('pending', 'waiting', 'in_progress', 'complete', 'failed', 'skipped', name='task_state'), server_default='pending', nullable=False),
    sa.Column('external_ref', sa.String(length=256), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'task_type', name='uq_booking_tasks_booking_id_task_type')
    )
    op.create_index('ix_booking_tasks_state', 'booking_tasks', ['state'], unique=False)
    op.create_table('data_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('email_parse', 'manual_entry', 'web_scrape', 'docusign_webhook', 'system_default', name='data_point_source'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_points_booking_field', 'data_points', ['booking_id', 'field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_data_points_booking_field', table_name='data_points')
    op.drop_table('data_points')
    op.drop_index('ix_booking_tasks_state', table_name='booking_tasks')
    op.drop_table('booking_tasks')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_check_in_date', table_name='bookings')
    op.drop_table('bookings')
    # Postgres keeps enum types when their tables are dropped; clean them up.
    bind = op.get_bind()
    for enum_name in (
        'data_point_source', 'task_state', 'task_type', 'booking_status', 'platform',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
